FROM apache/zeppelin:0.11.2

# Install required dependencies and Python 3.9
USER root
RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y python3.9 python3.9-dev python3.9-venv \
    && apt-get clean

# Update alternatives to point to the new Python version (Python 3.9)
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1 \
    && update-alternatives --set python3 /usr/bin/python3.9

# Install pip for the new Python version
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3 get-pip.py \
    && rm get-pip.py

# Install pyspark (or any other dependencies you need)
RUN pip3 install pyspark

# Set environment variables for Spark and Python
ENV PYSPARK_PYTHON=/usr/bin/python3.9
ENV PYSPARK_DRIVER_PYTHON=/usr/bin/python3.9

# Expose Zeppelin port
EXPOSE 8080

# Start Zeppelin
CMD ["/bin/bash", "/zeppelin/bin/zeppelin.sh"]
